#!/usr/bin/env python3

"""
Paste script, use with stdin

eg:

    git diff | nopaste

The resulting URL is copied to the clipboard and printed
"""

import sys
import lzma
import base64
import subprocess

base_url = "https://nopaste.boris.sh"

if sys.stdin.isatty():
    with open(sys.argv[1], 'r') as filedata:
        data = filedata.read()
else:
    data = sys.stdin.read()

# data = data.rstrip()
if not data:
    print("empty stdin! aborting")
    sys.exit(1)

data_compressed = lzma.compress(data.encode('utf-8'), format=2)
data_encoded = base64.b64encode(data_compressed)
final_url = "%s/#%s" % (base_url, data_encoded.decode('utf-8'))

# Print out the link
print("%s" % (final_url))

# Copy the link to the clipboard
p = subprocess.Popen(["xclip"], stdin=subprocess.PIPE)
p.communicate(input=final_url.encode('utf-8'))
